# Generated by Django 4.2.4 on 2023-08-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Category_EN/')),
                ('title', models.CharField(max_length=155, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Category_RU/')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Category_UZ/')),
                ('title', models.CharField(max_length=155, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=155, verbose_name='Familya')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Project/')),
                ('title_uz', models.CharField(max_length=155, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=155, verbose_name='Title')),
                ('pdf_uz', models.FileField(upload_to='PDF_uzb/', verbose_name='Uzbekcha PDF')),
                ('pdf_ru', models.FileField(upload_to='PDF_rus/', verbose_name='Русский PDF')),
                ('pdf_en', models.FileField(upload_to='PDF_eng/', verbose_name='English PDF')),
                ('price_uz', models.CharField(choices=[('0.5 - 1 million $', '0.5 - 1 million $'), ('1 - 5 million $', '1 - 5 million $'), ('5 - 10 million $', '5 - 10 million $'), ('10 - 15 million $', '10 - 15 million $'), ('15 - 20 million $', '15 - 20 million $'), ('20 - 25 million $', '20 - 25 million $'), ('25 - 30 million $', '25 - 30 million $'), ('30 + million $', '30 + million $')], max_length=155, verbose_name='Narxi')),
                ('price_ru', models.CharField(choices=[('0.5 - 1 миллион $', '0.5 - 1 миллион $'), ('1 - 5 миллион $', '1 - 5 миллион $'), ('5 - 10 миллион $', '5 - 10 миллион $'), ('10 - 15 миллион $', '10 - 15 миллион $'), ('15 - 20 миллион $', '15 - 20 миллион $'), ('20 - 25 миллион $', '20 - 25 миллион $'), ('25 - 30 миллион $', '25 - 30 миллион $'), ('30 + миллион $', '30 + миллион $')], max_length=155, verbose_name='Цена')),
                ('price_en', models.CharField(choices=[('0.5 - 1 million $', '0.5 - 1 million $'), ('1 - 5 million $', '1 - 5 million $'), ('5 - 10 million $', '5 - 10 million $'), ('10 - 15 million $', '10 - 15 million $'), ('15 - 20 million $', '15 - 20 million $'), ('20 - 25 million $', '20 - 25 million $'), ('25 - 30 million $', '25 - 30 million $'), ('30 + million $', '30 + million $')], max_length=155, verbose_name='Price')),
                ('description_uz', models.TextField(verbose_name='Tavsif')),
                ('description_ru', models.TextField(verbose_name='Описание')),
                ('description_en', models.TextField(verbose_name='Description')),
                ('category_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoryen', verbose_name='Category')),
                ('category_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoryru', verbose_name='Категория')),
                ('category_uz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoryuz', verbose_name='Kategoriya')),
            ],
        ),
    ]
